#!/usr/bin/env node
// ============================================
// SaveHatke AI — prepareData.js
// ============================================
// Builds the training corpus from its two sources and writes the derived files
// the other scripts consume:
//
//   data/ai/training/examples.jsonl   authored utterances  (source, kept)
//   data/ai/intents.json              seed utterances      (source, kept)
//   data/ai/training/intents.jsonl    merged + validated   (generated)
//   server/models/ai/vocabulary.json  token vocabulary     (generated by buildVocabulary)
//
// Validation is the point of this script: it fails loudly on a malformed line
// or an intent that is not in the taxonomy, so a typo cannot silently degrade
// classification.
//
// Run: npm run ai:prepare

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..');
const TRAINING_DIR = path.join(ROOT, 'data', 'ai', 'training');
const DATA_DIR = path.join(ROOT, 'data', 'ai');
const TAXONOMY_PATH = path.join(ROOT, 'server', 'models', 'ai', 'intents.json');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function readJsonl(file) {
  if (!fs.existsSync(file)) return [];
  return fs.readFileSync(file, 'utf8')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line, i) => {
      try {
        return JSON.parse(line);
      } catch (e) {
        throw new Error(`${path.relative(ROOT, file)}:${i + 1} is not valid JSON — ${e.message}`);
      }
    });
}

// A guard against training on something that must never enter the model.
// The brief is explicit: no emails, keys, tokens or real coupon codes.
const FORBIDDEN = [
  { name: 'email', re: /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/i },
  { name: 'api_key', re: /\b(sk|pk|rk)-[a-zA-Z0-9_-]{8,}|AIza[0-9A-Za-z_-]{20,}|sh_live_[A-Za-z0-9]{8,}/ },
  { name: 'jwt', re: /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\./ },
  { name: 'db_uri', re: /\b(mongodb|postgres|mysql|redis):\/\//i },
  { name: 'long_code', re: /\b[A-Z0-9]{10,16}\b/ },
];

function checkForbidden(text, where) {
  const problems = [];
  FORBIDDEN.forEach((rule) => {
    if (rule.re.test(text)) problems.push(`${rule.name} in ${where}: "${String(text).slice(0, 60)}"`);
  });
  return problems;
}

function main() {
  const taxonomy = readJson(TAXONOMY_PATH);
  const validIntents = new Set(Object.keys(taxonomy.intents || {}));

  const examples = readJsonl(path.join(TRAINING_DIR, 'examples.jsonl'));
  const seeds = readJson(path.join(DATA_DIR, 'intents.json'));

  const merged = [];
  const problems = [];
  const seen = new Set();

  const add = (text, intent, where) => {
    const t = String(text || '').trim();
    if (!t) return;
    if (!validIntents.has(intent)) {
      problems.push(`unknown intent "${intent}" in ${where}`);
      return;
    }
    checkForbidden(t, where).forEach((p) => problems.push(p));
    const key = `${intent}::${t.toLowerCase()}`;
    if (seen.has(key)) return;   // de-duplicate, keep first
    seen.add(key);
    merged.push({ text: t, intent });
  };

  examples.forEach((row, i) => {
    if (row.expectBlocked) return;              // security rows are not training data
    add(row.text, row.intent, `examples.jsonl:${i + 1}`);
  });

  Object.entries(seeds.intents || {}).forEach(([intent, list]) => {
    (list || []).forEach((t, i) => add(t, intent, `intents.json:${intent}[${i}]`));
  });

  // Shuffle deterministically so a train/test split is reproducible.
  let seed = 1337;
  const rand = () => {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff;
    return seed / 0x7fffffff;
  };
  for (let i = merged.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rand() * (i + 1));
    [merged[i], merged[j]] = [merged[j], merged[i]];
  }

  if (problems.length) {
    console.error('✗ Training data validation failed:');
    problems.forEach((p) => console.error(`  - ${p}`));
    process.exit(1);
  }

  const outPath = path.join(TRAINING_DIR, 'intents.jsonl');
  fs.writeFileSync(outPath, merged.map((r) => JSON.stringify(r)).join('\n') + '\n', 'utf8');

  // Distribution report — an intent with almost no examples cannot be learned.
  const counts = {};
  merged.forEach((r) => { counts[r.intent] = (counts[r.intent] || 0) + 1; });
  const thin = Object.entries(counts).filter(([, n]) => n < 5).map(([k, n]) => `${k}(${n})`);

  console.log('SaveHatke AI — data preparation');
  console.log(`  taxonomy intents : ${validIntents.size}`);
  console.log(`  examples.jsonl   : ${examples.length} rows`);
  console.log(`  intents.json     : ${Object.values(seeds.intents || {}).reduce((s, l) => s + l.length, 0)} seeds`);
  console.log(`  merged corpus    : ${merged.length} unique examples`);
  console.log(`  intents covered  : ${Object.keys(counts).length}`);
  console.log(`  written          : ${path.relative(ROOT, outPath)}`);
  if (thin.length) console.log(`  ⚠ thin intents   : ${thin.join(', ')}`);
  console.log('✓ done');
}

if (require.main === module) main();

module.exports = { readJsonl, readJson, checkForbidden, FORBIDDEN };